server:
    tomcat:
      uri-encoding: utf-8
    port: 8080

spring:
    datasource:
      url: jdbc:mysql://172.16.1.204:3306/test2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            enable_lazy_load_no_trans: true

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

    mvc:
       view: classpath:/templates
